## Exploratory Data Analysis

### Loading libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

### Importing the dataset

In [4]:
df=pd.read_csv("C:\\Users\\ashut\\OneDrive\\Desktop\\Global-Tech-Startup\\data\\raw\\global_tech_startups_2026.csv")

### Show the dataset

In [5]:
df.head()

,Company_ID,Domain,Founding_Year,Country,City,Funding_Stage,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026,Investor_Tier,AI_Adoption_Level,Acquisition_Status
0,B730AD52,HealthTech,2014,Canada,Montreal,Seed,1.64,17.81,1.46,0.33,3.8,23,0,23,Tier 3 (Angel/Seed),High,Independent
1,65A5F690,Web3/Crypto,2014,China,Beijing,Pre-IPO,103.87,949.16,32.77,2.42,41.2,242,146,96,Tier 3 (Angel/Seed),NaN,Closed
2,F106C853,Cybersecurity,2020,USA,San Francisco,Series A,10.08,43.37,2.16,1.01,9.1,59,0,59,Tier 2 (Mid-size VC),High,Independent
3,2BD798AF,FinTech,2023,India,Delhi NCR,Series B,32.28,257.62,11.66,0.78,36.7,76,0,76,Tier 3 (Angel/Seed),Medium,Independent
4,C5CB4451,Generative AI,2020,USA,New York,Series C+,13.41,76.73,2.57,1.12,11.0,59,28,31,Tier 2 (Mid-size VC),Medium,Closed

### Shape of the dataframe

In [6]:
df.shape

(25000, 17)

### Check the missing values

In [7]:
df.isnull().sum()

Company_ID                       0
Domain                           0
Founding_Year                    0
Country                          0
City                             0
Funding_Stage                    0
Total_Funding_USD_Millions       0
Valuation_USD_Millions           0
Revenue_ARR_Millions             0
Monthly_Burn_Rate_Millions       0
Runway_Months_2024               0
Peak_Headcount_2023              0
Layoffs_2024_2025                0
Current_Headcount_2026           0
Investor_Tier                    0
AI_Adoption_Level             2592
Acquisition_Status               0
dtype: int64

In [8]:
## Total null values
df.isnull().sum().sum()

2592

In [9]:
## Rows with missing values
df[df.isnull().any(axis=1)]

,Company_ID,Domain,Founding_Year,Country,City,Funding_Stage,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026,Investor_Tier,AI_Adoption_Level,Acquisition_Status
1,65A5F690,Web3/Crypto,2014,China,Beijing,Pre-IPO,103.87,949.16,32.77,2.42,41.2,242,146,96,Tier 3 (Angel/Seed),NaN,Closed
11,B976C5FE,Web3/Crypto,2020,USA,Seattle,Series A,29.70,106.15,6.46,1.45,19.2,133,60,73,Corporate VC (e.g. Google Ventures),NaN,Acquired
40,7153735A,Generative AI,2023,India,Delhi NCR,Series A,8.63,41.98,1.47,0.51,14.1,36,11,25,Tier 3 (Angel/Seed),NaN,Closed
51,5C40C7E2,Cybersecurity,2020,India,Mumbai,Seed,1.80,26.41,3.73,0.62,2.5,46,18,28,Tier 3 (Angel/Seed),NaN,Independent
58,83C88D10,Generative AI,2020,USA,New York,Series A,9.94,39.88,2.50,0.60,14.2,54,11,43,Tier 2 (Mid-size VC),NaN,Independent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24968,33E5E92F,HealthTech,2019,China,Beijing,Series A,2.50,42.64,1.54,0.24,7.4,16,9,7,Tier 3 (Angel/Seed),NaN,Closed
24972,2E6AADD3,EdTech,2019,Israel,Jerusalem,Series B,3.69,23.72,2.77,0.27,10.0,21,0,21,Tier 2 (Mid-size VC),NaN,Acquired
24974,CB34AF59,Autonomous Vehicles,2016,USA,Seattle,Series A,17.88,74.15,8.50,1.01,16.1,84,0,84,Tier 2 (Mid-size VC),NaN,Closed
24987,E5E4116B,HealthTech,2019,India,Delhi NCR,Series A,4.33,24.73,1.38,0.43,8.2,42,16,26,Tier 3 (Angel/Seed),NaN,Independent
24992,61C96935,Autonomous Vehicles,2020,India,Hyderabad,Pre-IPO,266.03,2925.81,528.15,16.06,16.5,1508,218,1290,"Tier 1 (e.g. Sequoia, a16z)",NaN,Closed

In [10]:
## Percentage of missing values
(df.isnull().sum().sum() / (df.shape[0] * df.shape[1])) * 100

0.6098823529411765

### Drop the missing value

In [11]:
df=df.dropna()

In [12]:
df.isnull().sum()

Company_ID                    0
Domain                        0
Founding_Year                 0
Country                       0
City                          0
Funding_Stage                 0
Total_Funding_USD_Millions    0
Valuation_USD_Millions        0
Revenue_ARR_Millions          0
Monthly_Burn_Rate_Millions    0
Runway_Months_2024            0
Peak_Headcount_2023           0
Layoffs_2024_2025             0
Current_Headcount_2026        0
Investor_Tier                 0
AI_Adoption_Level             0
Acquisition_Status            0
dtype: int64

In [13]:
df.head()

,Company_ID,Domain,Founding_Year,Country,City,Funding_Stage,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026,Investor_Tier,AI_Adoption_Level,Acquisition_Status
0,B730AD52,HealthTech,2014,Canada,Montreal,Seed,1.64,17.81,1.46,0.33,3.8,23,0,23,Tier 3 (Angel/Seed),High,Independent
2,F106C853,Cybersecurity,2020,USA,San Francisco,Series A,10.08,43.37,2.16,1.01,9.1,59,0,59,Tier 2 (Mid-size VC),High,Independent
3,2BD798AF,FinTech,2023,India,Delhi NCR,Series B,32.28,257.62,11.66,0.78,36.7,76,0,76,Tier 3 (Angel/Seed),Medium,Independent
4,C5CB4451,Generative AI,2020,USA,New York,Series C+,13.41,76.73,2.57,1.12,11.0,59,28,31,Tier 2 (Mid-size VC),Medium,Closed
5,22994DE8,Generative AI,2014,China,Shanghai,Series A,287.28,2399.01,190.65,5.00,56.3,500,0,500,Tier 3 (Angel/Seed),Low,Independent

In [14]:
df.shape

(22408, 17)

### Check the duplicate values

In [15]:
df.duplicated().sum()

0

#### No duplicates are found

### Check the data type

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22408 entries, 0 to 24999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Company_ID                  22408 non-null  object
 1   Domain                      22408 non-null  object
 2   Founding_Year               22408 non-null  int64
 3   Country                     22408 non-null  object
 4   City                        22408 non-null  object
 5   Funding_Stage               22408 non-null  object
 6   Total_Funding_USD_Millions  22408 non-null  float64
 7   Valuation_USD_Millions      22408 non-null  float64
 8   Revenue_ARR_Millions        22408 non-null  float64
 9   Monthly_Burn_Rate_Millions  22408 non-null  float64
 10  Runway_Months_2024          22408 non-null  float64
 11  Peak_Headcount_2023         22408 non-null  int64
 12  Layoffs_2024_2025           22408 non-null  int64
 13  Current_Headcount_2026      22408 non-null  int64
 14  Investor_Tier               22408 non-null  object
 15  AI_Adoption_Level           22408 non-null  object
 16  Acquisition_Status          22408 non-null  object
dtypes: float64(5), int64(4), object(8)
memory usage: 3.1+ MB

### Check the unique values

In [17]:
df.nunique()

Company_ID                    22408
Domain                           10
Founding_Year                    14
Country                          10
City                             29
Funding_Stage                     6
Total_Funding_USD_Millions     7933
Valuation_USD_Millions        15139
Revenue_ARR_Millions           6054
Monthly_Burn_Rate_Millions     2028
Runway_Months_2024              583
Peak_Headcount_2023            1670
Layoffs_2024_2025               611
Current_Headcount_2026         1542
Investor_Tier                     5
AI_Adoption_Level                 3
Acquisition_Status                5
dtype: int64

### Checking the statistics

In [18]:
df.describe()

,Founding_Year,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026
count,22408.000000,22408.000000,22408.000000,22408.000000,22408.000000,22408.000000,22408.000000,22408.000000,22408.000000
mean,2018.911505,60.001829,468.370988,33.246781,3.191484,12.184296,213.373126,32.138165,181.234961
std,2.812140,210.665799,1817.213144,137.503343,10.938244,10.079798,699.508460,181.600928,606.345845
min,2012.000000,0.000000,1.030000,0.050000,0.060000,0.000000,5.000000,0.000000,0.000000
25%,2017.000000,2.050000,28.950000,1.800000,0.430000,3.900000,30.000000,0.000000,22.000000
50%,2019.000000,8.470000,71.575000,4.810000,0.720000,10.600000,48.000000,0.000000,42.000000
75%,2021.000000,36.090000,267.572500,17.962500,2.240000,17.500000,154.000000,16.000000,119.000000
max,2025.000000,7867.390000,91692.420000,9021.530000,515.760000,89.600000,30086.000000,10280.000000,25657.000000

### Exploring Data

In [19]:
df.head()

,Company_ID,Domain,Founding_Year,Country,City,Funding_Stage,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026,Investor_Tier,AI_Adoption_Level,Acquisition_Status
0,B730AD52,HealthTech,2014,Canada,Montreal,Seed,1.64,17.81,1.46,0.33,3.8,23,0,23,Tier 3 (Angel/Seed),High,Independent
2,F106C853,Cybersecurity,2020,USA,San Francisco,Series A,10.08,43.37,2.16,1.01,9.1,59,0,59,Tier 2 (Mid-size VC),High,Independent
3,2BD798AF,FinTech,2023,India,Delhi NCR,Series B,32.28,257.62,11.66,0.78,36.7,76,0,76,Tier 3 (Angel/Seed),Medium,Independent
4,C5CB4451,Generative AI,2020,USA,New York,Series C+,13.41,76.73,2.57,1.12,11.0,59,28,31,Tier 2 (Mid-size VC),Medium,Closed
5,22994DE8,Generative AI,2014,China,Shanghai,Series A,287.28,2399.01,190.65,5.00,56.3,500,0,500,Tier 3 (Angel/Seed),Low,Independent

In [20]:
print("Categories in Domain :   ",end=" ")
print(df['Domain'].unique())

print("Categories in Country :   ",end=" ")
print(df['Country'].unique())

print("Categories in City :   ",end=" ")
print(df['City'].unique())

print("Categories in Funding stage :   ",end=" ")
print(df['Funding_Stage'].unique())

print("Categories in Investor Tier :   ",end=" ")
print(df['Investor_Tier'].unique())

print("Categories in AI Adoption Level :   ",end=" ")
print(df['AI_Adoption_Level'].unique())

print("Categories in Acquisition status :   ",end=" ")
print(df['Acquisition_Status'].unique())

Categories in Domain :    ['HealthTech' 'Cybersecurity' 'FinTech' 'Generative AI' 'EdTech'
 'ClimateTech' 'Robotics' 'SpaceTech' 'Web3/Crypto' 'Autonomous Vehicles']
Categories in Country :    ['Canada' 'USA' 'India' 'China' 'UK' 'Singapore' 'Germany' 'Israel'
 'Japan' 'France']
Categories in City :    ['Montreal' 'San Francisco' 'Delhi NCR' 'New York' 'Shanghai' 'Oxford'
 'Miami' 'Singapore' 'Cambridge' 'London' 'Bengaluru' 'Berlin' 'Seattle'
 'Mumbai' 'Hangzhou' 'Boston' 'Munich' 'Austin' 'Tel Aviv' 'Jerusalem'
 'Hyderabad' 'Beijing' 'Toronto' 'Shenzhen' 'Kyoto' 'Paris' 'Tokyo'
 'Vancouver' 'Lyon']
Categories in Funding stage :    ['Seed' 'Series A' 'Series B' 'Series C+' 'Pre-IPO' 'Post-IPO']
Categories in Investor Tier :    ['Tier 3 (Angel/Seed)' 'Tier 2 (Mid-size VC)'
 'Corporate VC (e.g. Google Ventures)' 'Tier 1 (e.g. Sequoia, a16z)'
 'Bootstrapped']
Categories in AI Adoption Level :    ['High' 'Medium' 'Low']
Categories in Acquisition status :    ['Independent' 'Closed' 'Acquired' 'IPO' 'Acquired (Fire Sale)']

In [21]:
## define numeric and categorical features
numeric_features=[feature for feature in df.columns if pd.api.types.is_numeric_dtype(df[feature])]
categorical_features=[feature for feature in df.columns if pd.api.types.is_categorical_dtype(df[feature]) 
                      or pd.api.types.is_object_dtype(df[feature])]

print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 9 numerical features : ['Founding_Year', 'Total_Funding_USD_Millions', 'Valuation_USD_Millions', 'Revenue_ARR_Millions', 'Monthly_Burn_Rate_Millions', 'Runway_Months_2024', 'Peak_Headcount_2023', 'Layoffs_2024_2025', 'Current_Headcount_2026']

We have 8 categorical features : ['Company_ID', 'Domain', 'Country', 'City', 'Funding_Stage', 'Investor_Tier', 'AI_Adoption_Level', 'Acquisition_Status']

In [22]:
df.head()

,Company_ID,Domain,Founding_Year,Country,City,Funding_Stage,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026,Investor_Tier,AI_Adoption_Level,Acquisition_Status
0,B730AD52,HealthTech,2014,Canada,Montreal,Seed,1.64,17.81,1.46,0.33,3.8,23,0,23,Tier 3 (Angel/Seed),High,Independent
2,F106C853,Cybersecurity,2020,USA,San Francisco,Series A,10.08,43.37,2.16,1.01,9.1,59,0,59,Tier 2 (Mid-size VC),High,Independent
3,2BD798AF,FinTech,2023,India,Delhi NCR,Series B,32.28,257.62,11.66,0.78,36.7,76,0,76,Tier 3 (Angel/Seed),Medium,Independent
4,C5CB4451,Generative AI,2020,USA,New York,Series C+,13.41,76.73,2.57,1.12,11.0,59,28,31,Tier 2 (Mid-size VC),Medium,Closed
5,22994DE8,Generative AI,2014,China,Shanghai,Series A,287.28,2399.01,190.65,5.00,56.3,500,0,500,Tier 3 (Angel/Seed),Low,Independent